name: .NET 8.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore
      run: dotnet restore KartSpec.csproj

    - name: Build
      run: dotnet build -c Release KartSpec.csproj

    - name: Publish
      run: dotnet publish -p:PublishProfile="Properties/PublishProfiles/FolderProfile.pubxml" -c Release

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KartSpec
        path: KartSpec.exe
